// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "bot-Alice/internal/logic/groupMessageEvent"
	_ "bot-Alice/internal/logic/login"
)
