// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

type (
	IChatGPT interface {
		GroupChat(code int64, msg string) (string, error)
		PrivateChat(code int64, msg string) (string, error)
	}
)

var (
	localChatGPT IChatGPT
)

func ChatGPT() IChatGPT {
	if localChatGPT == nil {
		panic("implement not found for interface IChatGPT, forgot register?")
	}
	return localChatGPT
}

func RegisterChatGPT(i IChatGPT) {
	localChatGPT = i
}
