// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"github.com/Mrs4s/MiraiGo/client"
	"github.com/Mrs4s/MiraiGo/message"
)

type (
	IGroupMessageEvent interface {
		Event(client *client.QQClient, event *message.GroupMessage)
	}
)

var (
	localGroupMessageEvent IGroupMessageEvent
)

func GroupMessageEvent() IGroupMessageEvent {
	if localGroupMessageEvent == nil {
		panic("implement not found for interface IGroupMessageEvent, forgot register?")
	}
	return localGroupMessageEvent
}

func RegisterGroupMessageEvent(i IGroupMessageEvent) {
	localGroupMessageEvent = i
}
